### ISSUE TITLE
Jekyll serve throws errors when serving default jekyll-bootstrap config

### ISSUE THREAD

**Issue by Wsadowski** [plusjade/jekyll-bootstrap#288]
When running jekyll serve in the directory cloned from the bootstrap repo, it throws a long list of errors:
```
Configuration file: /home/ws/Git/jekyll-bootstrap/_config.yml
/home/ws/Git/jekyll-bootstrap/_plugins/debug.rb:13:in `<module:Jekyll>': cannot load such file -- jekyll/post (LoadError)
        from /home/ws/Git/jekyll-bootstrap/_plugins/debug.rb:8:in `<top (required)>'
        from /home/ws/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/ws/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `each'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `each'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/lib/jekyll/site.rb:97:in `setup'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/lib/jekyll/site.rb:49:in `initialize'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `new'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `process'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from /home/ws/.gem/ruby/2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /home/ws/.gem/ruby/2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /home/ws/.gem/ruby/2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /home/ws/.gem/ruby/2.2.3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /home/ws/.gem/ruby/2.2.3/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /home/ws/.gem/ruby/2.2.3/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /home/ws/.gem/ruby/2.2.3/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
        from /home/ws/.gem/ruby/2.2.3/bin/jekyll:23:in `load'
        from /home/ws/.gem/ruby/2.2.3/bin/jekyll:23:in `<main>'
```
Serving a site generated by "jekyll new" works flawlessly, however.

**Comment by z007** [comment]
Hi **[Wsadowski](https://github.com/Wsadowski)**
This morning set up an environment also encountered the same problem. I just wrote a [__note__](https://github.com/z007/Environmental/blob/master/jekyllbootstrapl.md) to share with you.
gem install jekyll    #Default version jekyll 3.0.0     2015.11.1
gem uninstall jekyll  #Uninstall high version jekyll
gem install jekyll -v '2..5.3'

**Comment by brbrr** [comment]
problem goes to debug plugin. removing that one would resolve these errors

**Comment by timwis** [comment]
I've encountered this to using Jekyll v3.0.0. I resolved it by commenting out the first module in `debug.ru`

```ruby
require 'pp'
# module Jekyll
#   # Need to overwrite the inspect method here because the original
#   # uses < > to encapsulate the psuedo post/page objects in which case
#   # the output is taken for HTML tags and hidden from view.
#   #
#   class Post
#     def inspect
#       "#Jekyll:Post @id=#{self.id.inspect}"
#     end
#   end
  
#   class Page
#     def inspect
#       "#Jekyll:Page @name=#{self.name.inspect}"
#     end
#   end
  
# end # Jekyll
  
module Jekyll
  module DebugFilter
    
    def debug(obj, stdout=false)
      puts obj.pretty_inspect if stdout
      "<pre>#{obj.class}\n#{obj.pretty_inspect}</pre>"
    end

  end # DebugFilter
end # Jekyll

Liquid::Template.register_filter(Jekyll::DebugFilter)
```
